//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_Factura
    {
        public int num_detalle { get; set; }
        public int num_factura { get; set; }
        public int idTipoServicioProducto { get; set; }
        public int cantidadServicioProducto { get; set; }
        public double Precio { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual TipoServicioProducto TipoServicioProducto { get; set; }
    }
}
