//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.detalle_Factura = new HashSet<detalle_Factura>();
        }
    
        public int id_factura { get; set; }
        public string num_factura { get; set; }
        public System.DateTime fecha { get; set; }
        public int idCliente { get; set; }
        public int idVehiculo { get; set; }
        public double montoTotal { get; set; }
        public int estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<detalle_Factura> detalle_Factura { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual VehiculosCliente VehiculosCliente { get; set; }
    }
}
