//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public string id_factura { get; set; }
        public System.DateTime fecha { get; set; }
        public int idCliente { get; set; }
        public int idVehiculo { get; set; }
        public string numFactura { get; set; }
        public int id_estado { get; set; }
        public double montoTotal { get; set; }
        public int id_detalleFactura { get; set; }
    
        public virtual detalle_Factura detalle_Factura { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual VehiculosCliente VehiculosCliente { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
