//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaVehiculo
    {
        public MarcaVehiculo()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
        }
    
        public int idMarcaVehiculo { get; set; }
        public string codigo { get; set; }
        public int idPaisFabricante { get; set; }
        public string marca { get; set; }
    
        public virtual PaisFabricante PaisFabricante { get; set; }
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
