//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaisFabricante
    {
        public PaisFabricante()
        {
            this.MarcaVehiculo = new HashSet<MarcaVehiculo>();
        }
    
        public int idFabricante { get; set; }
        public string codigo { get; set; }
        public string pais { get; set; }
    
        public virtual ICollection<MarcaVehiculo> MarcaVehiculo { get; set; }
    }
}
