//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosVehiculo
    {
        public int idServiciosVehiculo { get; set; }
        public int idTipoServiciosProducto { get; set; }
        public int idVehiculo { get; set; }
        public int idClasificacionSP { get; set; }
        public int cantidad { get; set; }
        public double precio { get; set; }
        public double precioTotal { get; set; }
    
        public virtual TipoServicioProducto TipoServicioProducto { get; set; }
    }
}
