//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosCliente
    {
        public int idServiciosCliente { get; set; }
        public int idTipoServiciosProducto { get; set; }
        public int idCliente { get; set; }
        public int idClasificacionSP { get; set; }
        public int cantidad { get; set; }
        public double precio { get; set; }
        public double precioTotal { get; set; }
    
        public virtual clasificacionSP clasificacionSP { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual TipoServicioProducto TipoServicioProducto { get; set; }
    }
}
