//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosCliente
    {
        public int idServiciosCliente { get; set; }
        public int idTipoServiciosProducto { get; set; }
        public int idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoServicioProducto TipoServicioProducto { get; set; }
    }
}
