//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposVehiculo
    {
        public TiposVehiculo()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
            this.VehiculosCliente = new HashSet<VehiculosCliente>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int idTipoVehiculo { get; set; }
        public string codigo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
        public virtual ICollection<VehiculosCliente> VehiculosCliente { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
