//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicioProducto
    {
        public TipoServicioProducto()
        {
            this.detalle_Factura = new HashSet<detalle_Factura>();
            this.ServiciosCliente = new HashSet<ServiciosCliente>();
            this.ServiciosVehiculo = new HashSet<ServiciosVehiculo>();
        }
    
        public int idTipoServicioProducto { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public double precio { get; set; }
        public int tipo { get; set; }
    
        public virtual clasificacionSP clasificacionSP { get; set; }
        public virtual ICollection<detalle_Factura> detalle_Factura { get; set; }
        public virtual ICollection<ServiciosCliente> ServiciosCliente { get; set; }
        public virtual ICollection<ServiciosVehiculo> ServiciosVehiculo { get; set; }
    }
}
