//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposVehiculo
    {
        public TiposVehiculo()
        {
            this.Factura = new HashSet<Factura>();
            this.Vehiculos = new HashSet<Vehiculos>();
            this.VehiculosCliente = new HashSet<VehiculosCliente>();
        }
    
        public int idTipoVehiculo { get; set; }
        public string codigo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
        public virtual ICollection<VehiculosCliente> VehiculosCliente { get; set; }
    }
}
