//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicioProducto
    {
        public TipoServicioProducto()
        {
            this.detalle_Factura = new HashSet<detalle_Factura>();
        }
    
        public int idTipoServicioProducto { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public double precio { get; set; }
        public int tipo { get; set; }
    
        public virtual clasificacionSP clasificacionSP { get; set; }
        public virtual ICollection<detalle_Factura> detalle_Factura { get; set; }
    }
}
