//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosCliente
    {
        public VehiculosCliente()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public int idVehiculosCliente { get; set; }
        public int idVehiculo { get; set; }
        public int idCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
