//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public Vehiculos()
        {
            this.VehiculosCliente = new HashSet<VehiculosCliente>();
            this.ServiciosVehiculo = new HashSet<ServiciosVehiculo>();
            this.Factura = new HashSet<Factura>();
        }
    
        public int idVehiculos { get; set; }
        public string placa { get; set; }
        public int tipoVehiculo { get; set; }
        public int marcaVehiculo { get; set; }
        public int numeroPuerta { get; set; }
        public int numeroRueda { get; set; }
    
        public virtual MarcaVehiculo MarcaVehiculo1 { get; set; }
        public virtual TiposVehiculo TiposVehiculo { get; set; }
        public virtual ICollection<VehiculosCliente> VehiculosCliente { get; set; }
        public virtual ICollection<ServiciosVehiculo> ServiciosVehiculo { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
