//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistVehiculo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public Vehiculos()
        {
            this.VehiculosCliente = new HashSet<VehiculosCliente>();
        }
    
        public int idVehiculos { get; set; }
        public string placa { get; set; }
        public int tipoVehiculo { get; set; }
        public int marcaVehiculo { get; set; }
        public int numeroPuerta { get; set; }
        public int numeroRueda { get; set; }
    
        public virtual MarcaVehiculo MarcaVehiculo1 { get; set; }
        public virtual TiposVehiculo TiposVehiculo { get; set; }
        public virtual ICollection<VehiculosCliente> VehiculosCliente { get; set; }
    }
}
